### ISSUE TITLE
junk files

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/marcelo-paycheck#1]
Hi @MarceloBorgesP! There is no need to commit ```node_modules```. When you run the command ```npm install``` it will bring all the dependencies defined at ```package.json```.

![node_modules](https://cloud.githubusercontent.com/assets/5324414/10744259/c333437a-7c1f-11e5-90be-a4434e0fcb91.png)

**Comment by MarceloBorgesP** [comment]
Yeah I know.. if you look into the .gitignore file I put it there to be
ignored, I don't know why it was uploaded.

**Comment by edysegura** [comment]
Delete it and try again!

**Comment by MarceloBorgesP** [comment]
Okay, I'll do it.. thanks :)

**Comment by edysegura** [comment]
Pretty good!
